// Code generated by avro/gen. DO NOT EDIT.
package avro

import (
	"time"

	"github.com/hamba/avro/v2"
)

// A single aircraft state observation, derived from OpenSky-style ADS-B/MLAT/FLARM telemetry. Fields map directly to OpenSky's /states/all rows so the producer is a thin adapter; the consumer pipeline (Postgres / ClickHouse / Iceberg) treats this as the canonical wire shape.
type FlightTelemetry struct {
	// Unique observation ID (UUIDv4), generated per emission. Dedup key for sink-side broker-retry handling. Each poll snapshot is a distinct observation, so reusing a prior icao24's event_id is wrong.
	EventID string `avro:"event_id"`
	// ICAO 24-bit transponder address as 6-char lowercase hex. Primary aircraft identifier and Kafka partition key — preserves per-aircraft ordering across the topic.
	Icao24 string `avro:"icao24"`
	// Flight callsign (e.g. 'BAW123'). Null on private/ferry flights. The first 3 chars are the airline ICAO code; downstream rollups slice by this prefix.
	Callsign *string `avro:"callsign"`
	// Country of operator, derived from the icao24 prefix by OpenSky. NOT the aircraft's current geographic location. Used as the Iceberg partition column.
	OriginCountry string `avro:"origin_country"`
	// Observation time in microseconds since epoch (UTC). Prefers OpenSky's time_position when present; falls back to the envelope time.
	ObservedAt time.Time `avro:"observed_at"`
	// Origin of the position fix. ADS-B is the most precise; MLAT is multilateration from ground stations; FLARM is general-aviation collision-avoidance; UNKNOWN is the fallback when OpenSky's position_source is missing.
	PositionSource string `avro:"position_source"`
	// WGS-84 latitude in decimal degrees [-90, 90].
	Lat float64 `avro:"lat"`
	// WGS-84 longitude in decimal degrees [-180, 180].
	Lon float64 `avro:"lon"`
	// Barometric altitude in metres. Both altimeters are kept because they disagree (baro is the regulated value pilots fly to; geo is GPS-derived).
	BaroAltitudeM *float64 `avro:"baro_altitude_m"`
	// Geometric (GPS-derived) altitude in metres.
	GeoAltitudeM *float64 `avro:"geo_altitude_m"`
	// Ground speed in metres per second. Native OpenSky unit; analytics convert to km/h or knots at read time.
	VelocityMs *float64 `avro:"velocity_ms"`
	// True track over ground in decimal degrees clockwise from north [0, 360). North = 0, East = 90.
	TrueTrackDeg *float64 `avro:"true_track_deg"`
	// Rate of altitude change in metres per second. Positive = climbing, negative = descending. Threshold |2.5| m/s separates climb/descent from cruise in the rollups.
	VerticalRateMs *float64 `avro:"vertical_rate_ms"`
	// True if the position came from a surface report. on_ground=true aircraft typically have null velocity and altitude.
	OnGround bool `avro:"on_ground"`
	// Transponder code as a 4-digit octal string. Special codes: 7500 (hijack), 7600 (radio failure), 7700 (general emergency); analytics surface these as anomaly counts.
	Squawk *string `avro:"squawk"`
	// Special Purpose Indicator. ATC-requested ident; rare but useful in anomaly views.
	Spi bool `avro:"spi"`
	// OpenSky aircraft category 0-20 (light/small/medium/heavy/etc.). Optional; many sources don't broadcast it.
	Category *int `avro:"category"`
}

var schemaFlightTelemetry = avro.MustParse(`{"name":"com.dreamflight.FlightTelemetry","type":"record","fields":[{"name":"event_id","type":{"type":"string","logicalType":"uuid"}},{"name":"icao24","type":"string"},{"name":"callsign","type":["null","string"]},{"name":"origin_country","type":"string"},{"name":"observed_at","type":{"type":"long","logicalType":"timestamp-micros"}},{"name":"position_source","type":{"name":"com.dreamflight.PositionSource","type":"enum","symbols":["ADSB","ASTERIX","MLAT","FLARM","UNKNOWN"]}},{"name":"lat","type":"double"},{"name":"lon","type":"double"},{"name":"baro_altitude_m","type":["null","double"]},{"name":"geo_altitude_m","type":["null","double"]},{"name":"velocity_ms","type":["null","double"]},{"name":"true_track_deg","type":["null","double"]},{"name":"vertical_rate_ms","type":["null","double"]},{"name":"on_ground","type":"boolean"},{"name":"squawk","type":["null","string"]},{"name":"spi","type":"boolean"},{"name":"category","type":["null","int"]}]}`)

// Schema returns the schema for FlightTelemetry.
func (o *FlightTelemetry) Schema() avro.Schema {
	return schemaFlightTelemetry
}

// Unmarshal decodes b into the receiver.
func (o *FlightTelemetry) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *FlightTelemetry) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
