// Package avro contains the Avro-serialized flight telemetry types and the
// canonical schema embedded for runtime use.
//
// flight_telemetry.go is generated by avrogen from flight_telemetry.avsc;
// see the go:generate directive below. Run `make gen` after editing the schema.
package avro

import _ "embed"

// CanonicalSchema is the canonical Avro schema for FlightTelemetry, embedded at
// build time. It has the full doc comments and defaults needed for BACKWARD
// compatibility evolution under Confluent Schema Registry. Producers register
// this exact byte sequence; downstream consumers should fetch by ID from SR
// rather than re-embedding.
//
//go:embed flight_telemetry.avsc
var CanonicalSchema []byte

// Regenerate flight_telemetry.go from the Avro schema:
//
//go:generate go run github.com/hamba/avro/v2/cmd/avrogen -pkg avro -encoders -o flight_telemetry.go flight_telemetry.avsc
