// Package avro contains the Avro-serialized movement event types and the
// canonical schema embedded for runtime use.
//
// movement_event.go is generated by avrogen from movement_event.avsc;
// see the go:generate directive below. Run `make gen` after editing the schema.
package avro

import _ "embed"

// CanonicalSchema is the canonical Avro schema for MovementEvent, embedded at
// build time. It has the full doc comments and defaults needed for BACKWARD
// compatibility evolution under Confluent Schema Registry. Producers register
// this exact byte sequence; downstream consumers should fetch by ID from SR
// rather than re-embedding.
//
//go:embed movement_event.avsc
var CanonicalSchema []byte

// Regenerate movement_event.go from the Avro schema:
//
//go:generate go run github.com/hamba/avro/v2/cmd/avrogen -pkg avro -encoders -o movement_event.go movement_event.avsc
