// Code generated by avro/gen. DO NOT EDIT.
package avro

import (
	"time"

	"github.com/hamba/avro/v2"
)

// A single location/movement update for a mobile entity. Flattened from the nested JSON input (entity.type → entity_type, position.lat → lat) for query efficiency. The ingestion API maps the nested JSON shape to this flat Avro record.
type MovementEvent struct {
	// Unique event identifier (UUID). Used as the dedup key across all sinks.
	EventID string `avro:"event_id"`
	// Entity kind: vehicle, courier, scooter, device, etc.
	EntityType string `avro:"entity_type"`
	// Entity identifier, unique within entity_type.
	EntityID string `avro:"entity_id"`
	// Event timestamp in microseconds since epoch (UTC). Used for out-of-order detection in the timestamp-gated upsert.
	Timestamp time.Time `avro:"timestamp"`
	// Latitude in decimal degrees [-90, 90].
	Lat float64 `avro:"lat"`
	// Longitude in decimal degrees [-180, 180].
	Lon float64 `avro:"lon"`
	// Speed in km/h. Optional — may be absent from the source event.
	SpeedKmh *float64 `avro:"speed_kmh"`
	// Heading in degrees [0, 360). Optional.
	HeadingDeg *float64 `avro:"heading_deg"`
	// Positional accuracy in metres. Optional.
	AccuracyM *float64 `avro:"accuracy_m"`
	// Source of the position fix: gps, wifi, cell, etc. Optional.
	Source *string `avro:"source"`
	// Arbitrary key-value metadata as a JSON-encoded string. Stored opaque in Avro to avoid complex union-in-map types; parsed downstream where needed. Example: '{"battery_level":0.82}'.
	Attributes *string `avro:"attributes"`
}

var schemaMovementEvent = avro.MustParse(`{"name":"com.dreammobility.MovementEvent","type":"record","fields":[{"name":"event_id","type":{"type":"string","logicalType":"uuid"}},{"name":"entity_type","type":"string"},{"name":"entity_id","type":"string"},{"name":"timestamp","type":{"type":"long","logicalType":"timestamp-micros"}},{"name":"lat","type":"double"},{"name":"lon","type":"double"},{"name":"speed_kmh","type":["null","double"]},{"name":"heading_deg","type":["null","double"]},{"name":"accuracy_m","type":["null","double"]},{"name":"source","type":["null","string"]},{"name":"attributes","type":["null","string"]}]}`)

// Schema returns the schema for MovementEvent.
func (o *MovementEvent) Schema() avro.Schema {
	return schemaMovementEvent
}

// Unmarshal decodes b into the receiver.
func (o *MovementEvent) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *MovementEvent) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
