apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: df-postgres-retention
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nis94/dream-flight.git
    targetRevision: main
    path: deploy/helm/postgres-retention
    helm:
      releaseName: df-postgres-retention
      valueFiles:
        - values.yaml
        - values-kind.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
