apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: df-stream-processor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/nis94/dream-flight.git
    targetRevision: main
    path: deploy/helm/stream-processor
    helm:
      releaseName: df-stream-processor
      valueFiles:
        - values.yaml
        - values-kind.yaml
      parameters:
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
